---
addons:
  chrome: stable
before_install: "cd ./Client"
cache:
  directories:
    - ./node_modules
dist: trusty
install:
  - "npm install"
language: node_js
node_js:
  - "12.14.0" 
script:
  - "npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox"
sudo: false
